server:
  port: 2323
spring:
  cloud:
    gateway:
      routes:
      - id: baeldung_route
        uri: http://www.baeldung.com:80
        predicates:
        - Path=/baeldung
management:
  security:
    enabled: false
#
# okta:
#   oauth2:
#     issuer: https://{yourOktaDomain}.com/oauth2/default
#     clientId: {yourClientId}
#     clientSecret: {yourClientSecret}
#
# # Configure the callback URL to match the previous section
# security:
#   oauth2:
#     sso:
#       loginPath: /authorization-code/auth
